actsIn(carolynWang, wangalanger) .
actsIn(nikkiWong, wangalanger) .
actsIn(carolynWang, wangman) .
actsIn(carolynWang, wangdanger) .
actsIn(balinBanh, stumps) .
actsIn(beverlyLi, stumps) .
actsIn(beverlyLi, beverlily) .
actsIn(beverlyLi, beverlily2) .
actsIn(nikkiWong, wangVsWong) .
actsIn(balinBanh, battleOfTheStumps) .
actsIn(beverlyLi, battleOfTheStumps) .
directs(michaelBay, transformers) .
directs(nikkiWong, wangalanger) .
directs(carolynWang, wangdanger) .
directs(carolynWang, wangman) .
directs(beverlyLi, beverlily) .
directs(beverlyLi, beverlily2) .
directs(carolynWang, stumps) .
directs(nikkiWong, battleOfTheStumps) .
directs(jonFavreau, avengers) .
directs(christopherNolan, theDarkKnight) .
released(theGodfather, 1972) .
released(theDarkKnight, 2008) .
released(monstersInc, 2001) .
released(wangalanger, 2016) .
released(avengers, 2012) .
released(pokemon, 2000) .
released(wangman, 2017) .
released(wangVsWong, 2019) .
released(frozen, 2013) .
released(transformers, 2007) .
released(wangdanger, 2018) .
released(stumps, 2017) .
released(beverlily, 2016) .
released(beverlily2, 2017) .
released(battleOfTheStumps, 2018) .
